name: Package Azure Function
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd network-traffic
          npm install --omit=dev
      - run: |
          cd storage-logs
          npm install --omit=dev
      - name: Zip Folder
        run: |
          cd network-traffic && zip -r ../network-traffic-collector.zip . -x ".git/*" ".github/*" ".vscode/*"
          cd ../storage-logs && zip -r ../storage-logs-collector.zip . -x ".git/*" ".github/*" ".vscode/*"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: 1.0.2
          tag_name: ${{ github.ref }}
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload network collector artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: ${{ steps.create_release.outputs.upload_url }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: network-traffic-collector.zip
          asset_name: network-traffic-collector.zip
          asset_content_type: application/zip
      - name: upload storage collector artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: ${{ steps.create_release.outputs.upload_url }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: storage-logs-collector.zip
          asset_name: storage-logs-collector.zip
          asset_content_type: application/zip