name: Package Azure Function
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install --omit=dev
      - name: Zip Folder
        run: |
          zip -r azure-log-collectors.zip . -x ".git/*" ".github/*" ".vscode/*"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: 1.0.1
          tag_name: ${{ github.ref }}
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: ${{ steps.create_release.outputs.upload_url }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: azure-log-collectors.zip
          asset_name: azure-log-collectors.zip
          asset_content_type: application/zip
